---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision VM from Template
    name: template
    inherits: 
    description: 
  fields:
  - AcquireIPAddress:
      value: "/General/phpipam/get_ip"
  - RegisterDNS:
      value: "/General/dns_config/add_dns"
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
  - AddCustomAttribute:
      value: "/General/add_custom_attribute/add_custom_attribute"
